module.exports = {
	MONGODB: process.env.MONGO_DB,
	SECRET_KEY: process.env.SECRET_KEY,
	CLIENT_URL: process.env.CLIENT_URL,
	SERVER_EMAIL_ADDRESS: process.env.SERVER_EMAIL_ADDRESS,
	SERVER_EMAIL_PASSWORD: process.env.SERVER_EMAIL_PASSWORD,
};
